### ISSUE TITLE
PSA: invidio.us is now invidious.io

### ISSUE THREAD

**Issue by Mennaruuk** [SiIky/invidious#1]
[Announcement](https://github.com/iv-org/invidious/issues/1694). Please spread the message to anyone still using invidio.us!

"invidio.us is now deprecated, [invidious.io](https://invidious.io) is the new domain.

The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo.

Projects using something from invidio.us need to move to the new domain."

**Comment by siiky** [comment]
Wow I'm so sorry I didn't reply to you sooner! I don't know why, but I didn't get any notification -- have to check that out...

Now, to the point: It seems the site isn't there (I tried using it as the instance on `ivp`). And according to https://github.com/iv-org/invidious/issues/1694#issuecomment-800941029 they decided not to go forward. If you have any news from outside that issue, please do share! I've been looking for a good and reliable instance with API calls support for a while now.

**Comment by Mennaruuk** [comment]
Not a problem!

Hmm, that’s weird. I think the linked comment talks about setting up an official instance at invidious.io, which would be too expensive. Not sure what the site will exactly do, but there is an announcement there about something coming soon. I’m concerned because the organizer TheFrenchGhosty said the old sites are deprecated and should no longer be used, and I’m not sure when the old sites will stop working. 

I’m looking at https://uptime.invidious.io. I see some instances have been excellent for a long while. Are ones like invidious.tube and invidious.xyz good? They seem to have excellent uptime, but I don’t know if they support API calls.

**Comment by siiky** [comment]
I didn't know about that uptime page, it's neat!

 * `invidious.tube` gives 0 results;
 * `invidious.xyz` returns 502.
 * The current default instance of this library (`invidious.snopyta.org`) used to support (allow?) API calls but no longer -- returns 403;
 * One instance I just learned of from someone (`invidious.himiko.cloud`) seems to be working well;
 * And so does `inv.skyn3t.in` (picked now from the uptime page);
 * `invidous.site` and `invidiou.site` sometimes work, some times don't -- they return no results, or timeout.

Big mess. I wonder what I should do about the default instance of the library -- they can just vanish, like `invidio.us`, or start blocking API calls, like `invidious.snopyta.org`... :/ Don't know if it's in their (`invidious.io`) plans, but it would be cool if they had an endpoint to get a list of "good" instances.

But anyway, thanks for alerting me about this!

I'll keep this issue open as a reminder that I have to do something about it, but you can unsubscribe if you want. :)

**Comment by siiky** [comment]
Just learned of [this endpoint](https://api.invidious.io/instances.json?sort_by=health) from [kssytsrk/nx-freestance-handler](https://github.com/kssytsrk/nx-freestance-handler/blob/38baaafa328b6d1beb058949e9e892d500276f78/invidious-handler.lisp#L35-L48). It seems like it is what I'm looking for.

**Comment by Mennaruuk** [comment]
That’s great!

**Comment by siiky** [comment]
Opened https://github.com/iv-org/instances-api/issues/24 but no one has replied yet.

**Comment by siiky** [comment]
First step towards better handling of instances: 026cfeeca43699a268e390c568315c99ca27e586

**Comment by siiky** [comment]
Implemented automatic instance fallback on [`ivp`](https://github.com/siiky/ivp), based on the above mentioned commit: https://github.com/siiky/ivp/commit/4e12b246b23b71850324342e6384fe146f07fb23 & https://github.com/siiky/ivp/commit/92b3328785b11c4ffeb2df53d0f1aa720e41b238

**Comment by siiky** [comment]
https://github.com/iv-org/instances-api/issues/24 has been implemented and closed! The `instances.json` now includes an `api` field to mean whether an instance accepts or not API requests.

Maybe this weekend...
